<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="">
    <head>
        <title>Administration</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" media="screen" href="/public/stylesheets/crud.css" />
    </head>
    <body id="crud">
        <div id="crudHeader">
            <h1><a href="/admin/">Administration</a></h1>
        </div>

        <div id="crudContent">

<div id="crudIndex">

    <h2>Choose the object to edit</h2>

    <table>
        <thead>
            <tr>
                <th>Object type</th>
                <th width="20%"></th>
            </tr>
        </thead>
        <tbody>

	                <tr>
                <td>
                    <a href="/admin/users">Users</a>
                </td>
                <td class="crudNew" >
                    <a href="/admin/users/new">Add</a>
                </td>
            </tr>
        </tbody>
    </table>

</div>
        </div>

        <div id="crudFooter">
            Generated by the Play CRUD module. <a href="http://www.playframework.org/documentation/1.1/crud">Learn how to customize it !</a>
        </div>

    </body>
</html>
